//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id { get; set; }
        public int Admin_ID { get; set; }
        public string Password { get; set; }
        public Nullable<int> FK_College_Id { get; set; }
    
        public virtual college_tbl college_tbl { get; set; }
    }
}
