//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendanceTrackrEntities : DbContext
    {
        public AttendanceTrackrEntities()
            : base("name=AttendanceTrackrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendanceTbl> AttendanceTbls { get; set; }
        public virtual DbSet<college_tbl> college_tbl { get; set; }
        public virtual DbSet<course_tbl> course_tbl { get; set; }
        public virtual DbSet<department_tbl> department_tbl { get; set; }
        public virtual DbSet<hostel_tbl> hostel_tbl { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<semester_tbl> semester_tbl { get; set; }
        public virtual DbSet<student_tbl> student_tbl { get; set; }
        public virtual DbSet<Teacher_tbl> Teacher_tbl { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<year_tbl> year_tbl { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
