//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceTbl
    {
        public int attendance_id { get; set; }
        public int student_id { get; set; }
        public Nullable<bool> isPresent { get; set; }
        public Nullable<System.DateTime> attendance_date { get; set; }
        public string marked_by { get; set; }
    }
}
