//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_tbl
    {
        public int student_id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Student_Type { get; set; }
        public Nullable<int> FK_Dept_Id { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> FK_Collage_Id { get; set; }
        public Nullable<int> FK_Year_Id { get; set; }
        public Nullable<int> FK_Sem_Id { get; set; }
        public Nullable<int> FK_Course_Id { get; set; }
        public Nullable<int> FK_Hostel_Id { get; set; }
        public System.DateTime Created_date { get; set; }
        public string Created_by { get; set; }
        public string Password { get; set; }
        public int Id { get; set; }
    
        public virtual college_tbl college_tbl { get; set; }
        public virtual course_tbl course_tbl { get; set; }
        public virtual department_tbl department_tbl { get; set; }
        public virtual hostel_tbl hostel_tbl { get; set; }
        public virtual semester_tbl semester_tbl { get; set; }
        public virtual year_tbl year_tbl { get; set; }
    }
}
