//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_tbl
    {
        public int Id { get; set; }
        public int Faculty_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> FK_Dept_Id { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public string Created_by { get; set; }
        public string Password { get; set; }
    
        public virtual department_tbl department_tbl { get; set; }
    }
}
